### PR TITLE
fix #6315 no member named 'GetCocoaServer'

### LINKED ISSUE #6315: no member named 'GetCocoaServer'
Hi;
When I compile openCV 3 (HEAD) version, it has been broken compiling.
I can use PCL and VTK normaly.
How can I solve this problem.

```
/tmp/opencv320160323-37738-fjug24/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:284:81: error: no member named 'GetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
        vtkCocoaServerFix *server = reinterpret_cast<vtkCocoaServerFix*> (this->GetCocoaServer ());
                                                                          ~~~~  ^
/tmp/opencv320160323-37738-fjug24/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:285:20: error: no member named 'GetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
        if (!this->GetCocoaServer ())
             ~~~~  ^
/tmp/opencv320160323-37738-fjug24/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:288:19: error: no member named 'SetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
            this->SetCocoaServer (reinterpret_cast<void*> (server));
            ~~~~  ^
/tmp/opencv320160323-37738-fjug24/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:300:81: error: no member named 'GetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
        vtkCocoaServerFix *server = reinterpret_cast<vtkCocoaServerFix*> (this->GetCocoaServer ());
                                                                          ~~~~  ^
4 errors generated.
make[2]: *** [modules/viz/CMakeFiles/opencv_viz.dir/src/vtk/vtkCocoaInteractorFix.mm.o] Error 1
make[1]: *** [modules/viz/CMakeFiles/opencv_viz.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

### PR DESCRIPTION
**Pull request by solosuper**
resolves #6315

### What does this PR change?
Change `modules/viz/src/vtk/vtkCocoaInteractorFix.mm` to correctly test VTK version.

### CODE REVIEW

File: modules/viz/src/vtk/vtkCocoaInteractorFix.mm [hunk 1]
```diff
@@ -160,7 +160,7 @@ - (void)windowWillClose:(NSNotification*)aNotification
 
 //----------------------------------------------------------------------------
 
-#if VTK_MAJOR_VERSION >= 6 && VTK_MINOR_VERSION  >=2
+#if VTK_MAJOR_VERSION >= 6 && VTK_MINOR_VERSION >=2 || VTK_MAJOR_VERSION >=7
```
Comment (alalek) [inline modules/viz/src/vtk/vtkCocoaInteractorFix.mm]: I believe this condition is more readable:
```
#if (VTK_MAJOR_VERSION * 100 + VTK_MINOR_VERSION) >= 602  // 6.2
```

Comment (solosuper) [inline modules/viz/src/vtk/vtkCocoaInteractorFix.mm]: Well, I am not sure if I agree on "more readable", but you decide : )

Do you want me to fix it?

**Comment by alalek** [comment]
:+1:
