### PR TITLE
ffmpeg: interrupt callback fix

### LINKED ISSUE #6356: Videocapture *mov`s seems to time out in virtualbox
From: http://answers.opencv.org/question/91532/videocapture-movs-seems-to-time-out-in-virtualbox/)

I get a strange behavior with Videocapture when I run code inside a Virtualbox client (Client: Ubuntu 15.10 x64) (confirmed with following host systems: Windows & Arch Linux). When the Videocapture object opens a video file everything is fine but when the system idles for too long (e.g. waiting for keyboard input) ~30 seconds the video capture returns an empty list and not the next frame of the video file (VideoCapture::grab returns false). This only seem to happen with *.mov files like the one attached (http://80.86.85.151:91/small.mov). Is this a problem in OpenCV or might something else be the cause?

### Please state the information for your system
- OpenCV version: 3.1.x (current OpenCV master branch)
- "Host" OS: Linux (Ubuntu 15.10) as Virtualbox VM, strangly, outside the virtual machine everything works fine (Outside host systems: Windows and Arch)

### In which part of the OpenCV library you got the issue?
- videoio

### Expected behaviour
when idle for some time, VideoCapture objects deliver the next frame when asked to.

### Actual behaviour
when idle for some time, VideoCapture objects seem to "time out" and deliver empty Mat`s. VideoCapture::grab already returns false!

### Additional description
The issue only seem to happen inside of a virtualbox image of Ubuntu 15.10 x64. When executed on the host, no problems occur.

### Code example to reproduce the issue / Steps to reproduce the issue

Video file: [small.mov.zip](https://github.com/Itseez/opencv/files/199955/small.mov.zip)

```cpp
#include <cv.h>
#include <highgui.h>
#include <opencv2/core/core.hpp> 
#include <opencv2/videoio/videoio.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <string>
#include <iostream>

using namespace cv;
using namespace std;

int main(){

const string ref = "/home/biotracker/Downloads/MVI_7555.MOV";

cv::VideoCapture capt(ref); 
Mat im;
capt >> im;

for (int i = 0; i < 10; i++) {
    cout << "im empty: " << im.empty() << endl;     
    imshow("qq", im);
    char c = waitKey(60000);
    cout << "time is over, nextframe" << endl;
    capt >> im;
}

return 0;
}
```

### PR DESCRIPTION
**Pull request by alalek**
resolves #6356

Use timeout interrupt only for active waits (during `open` or `read` calls).

### CODE REVIEW

File: modules/videoio/src/cap_ffmpeg_impl.hpp [hunk 1]
```diff
@@ -394,6 +395,11 @@ inline int _opencv_ffmpeg_interrupt_callback(void *ptr)
     AVInterruptCallbackMetadata* metadata = (AVInterruptCallbackMetadata*)ptr;
     assert(metadata);
 
+    if (metadata->timeout_after_ms == 0)
```
Comment (peters) [inline modules/videoio/src/cap_ffmpeg_impl.hpp]: `<= 0`

File: modules/videoio/src/cap_ffmpeg_impl.hpp [hunk 2]
```diff
@@ -2717,14 +2742,23 @@ bool InputMediaStream_FFMPEG::read(unsigned char** data, int* size, int* endOfFi
...
         }
 
+        result = true;
         break;
     }
 
-    *data = pkt_.data;
-    *size = pkt_.size;
-    *endOfFile = false;
+#if USE_AV_INTERRUPT_CALLBACK
```
Comment (peters) [inline modules/videoio/src/cap_ffmpeg_impl.hpp]: Isn't there a postfix missing here since the intention is to disable the aforementioned behavior?

File: modules/videoio/src/cap_ffmpeg_impl.hpp (hunk 1 above)
Comment (alalek) [inline modules/videoio/src/cap_ffmpeg_impl.hpp]: It is "unsigned" (line 381)

File: modules/videoio/src/cap_ffmpeg_impl.hpp (hunk 2 above)
Comment (peters) [inline modules/videoio/src/cap_ffmpeg_impl.hpp]: Btw, should these values be read from current environment? Because then if you'd want to disable current behavior you could set an infinite value.

Comment (alalek) [inline modules/videoio/src/cap_ffmpeg_impl.hpp]: Sorry, I'm not sure that I understand this question.
Could you describe problem with more details?

Behaviour of this function is changed in case of this [`break` (line 2723)](https://github.com/Itseez/opencv/pull/6358/files/7d9a4805978394176eefbc4e53821fc862ed39cf#diff-d8eb3db25b0d9d1bb7b4355d5d56e006R2723) - we don't return "true" in case of reached timeout. And this [`break` (line 2736)](https://github.com/Itseez/opencv/pull/6358/files/7d9a4805978394176eefbc4e53821fc862ed39cf#diff-d8eb3db25b0d9d1bb7b4355d5d56e006R2736) gets timeout deactivation. Other code paths should be fine.

Comment (alalek) [inline modules/videoio/src/cap_ffmpeg_impl.hpp]: I use ["zero"](https://github.com/Itseez/opencv/pull/6358/files/7d9a4805978394176eefbc4e53821fc862ed39cf#diff-d8eb3db25b0d9d1bb7b4355d5d56e006R398) value instead of "infinite".

**Comment by alalek** [comment]
:+1:
