### PR TITLE
Bug fix for MLP predict for small values to avoid nan responses.

### LINKED ISSUE #6394: ANN_MLP 'predict' function returns -nan for large input signal
### System Information
- OpenCV  3.1
- Host OS: Linux (Xubuntu 14.04.1)  

### In which part of the OpenCV library you got the issue?
- On ANN_MLP class ( machine learning module)
- ANN_MLP predictions return -nan in cases where the input signal is too high when SIGMOID_SYM activation function is used.

### Expected behaviour
- -beta (param2)

### Actual behaviour
- -nan

### Additional description
I've found the bug at "modules/ml/src/ann_mlp.cpp" on line 435.
It isn't checked if the result of exp function on line 419 returns -inf. The activation function is calculated with '-inf' value and '-nan' is returned. 

To fix this bug, I've replaced the lines 435 and 436 for the code below
```
if(!cvIsInf(data[j])){
         double t = scale2*(1. - data[j])/(1. + data[j]);
         data[j] = t;
}else{
         data[j] = -f_param2;
}
```

### PR DESCRIPTION
**Pull request by Tauranis**
resolves #6394  

### What does this PR change?
It isn't checked if the result of exp function on line 419 returns -inf. The activation function is calculated with '-inf' value and '-nan' is returned. 

To fix this bug, I've replaced the lines 435 and 436 for the code below
```
if(!cvIsInf(data[j]))
{
      double t = scale2*(1. - data[j])/(1. + data[j]);
      data[j] = t;
}
else
{
      data[j] = -scale2;
}
```

### CODE REVIEW

File: modules/ml/src/ann_mlp.cpp [hunk 1]
```diff
@@ -432,8 +432,12 @@ class ANN_MLPImpl : public ANN_MLP
                     double* data = sums.ptr<double>(i);
                     for( j = 0; j < cols; j++ )
                     {
-                        double t = scale2*(1. - data[j])/(1. + data[j]);
-                        data[j] = t;
+                        if(!cvIsInf(data[j])){
+                            double t = scale2*(1. - data[j])/(1. + data[j]);
+                            data[j] = t;
+                        }else{
+                            data[j] = -f_param2;
```
Comment (mshabunin) [inline modules/ml/src/ann_mlp.cpp]: I'd suggest to use `-scale2` here for consistency.
Please use same curly braces format as in the whole file:
```.cpp
if ()
{
    // ...
}
else
{
    // ...
}
```

**Comment by Tauranis** [comment]
Modification done!!!

Thanks for the fast response.

File: modules/ml/src/ann_mlp.cpp (hunk 1 above)
Comment (Tauranis) [inline modules/ml/src/ann_mlp.cpp]: Modification done!!!

Thanks for the fast response.

**Comment by mshabunin** [comment]
Thank you. Please squash both commits into one.

**Comment by Tauranis** [comment]
Squash done!!!

**Comment by mshabunin** [comment]
:+1:
